### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by roobie** [mirontoli/sql-max#24]
We should choose to use GiB for the unit in the UI
or
use `var oneGb = 1000; //MB` in the calculations

since:

one GB === 1000 MB === 1 000 000 000 B
one GiB === 1024 MiB === 2^30 B

(Reference1)[http://www.wolframalpha.com/input/?i=1+gb]

(Reference2)[http://www.wolframalpha.com/input/?i=1+gib]

**Comment by timw-be** [comment]
Hi,
Stumbled on this while trying to replicate the formula in PowerShell and consistently getting different values compared to the web app. This change does not seem to have made it into the web app, as it still counts 1 GB = 1000. Any reason why this was not implemented?
Personally I find it strange to use 1 GB = 1000, while later on in the formula you calculate (1 GB * ($TotalCPUCores / 4)), where 1 GB is manually defined as 1024.
It seems a bit inconsistent, doesn't it?
